apiVersion: apps/v1
kind: Deployment
metadata:
    name: fusionauth
    labels:
        task: fusionauth
spec:
    replicas: 1
    selector:
        matchLabels:
            task: fusionauth
    template:
        metadata:
            labels:
                task: fusionauth
        spec:
            nodeSelector:
                eks.amazonaws.com/compute-type: fargate
            containers:
                - name: fusionauth
                  image: fusionauth/fusionauth-app:1.27.2
                  ports:
                    - containerPort: 9011
                  livenessProbe:
                    httpGet:
                        path: /api/status
                        port: 9011
                    initialDelaySeconds: 60
                    periodSeconds: 60
                    timeoutSeconds: 30
                  readinessProbe:
                    httpGet:
                        path: /api/status
                        port: 9011
                    initialDelaySeconds: 60
                    timeoutSeconds: 30
                  resources:
                    requests:
                        cpu: "500m"
                        memory: "2Gi"
                  env:
                    - name: DATABASE_URL
                      value: "jdbc:postgresql://{{ .Values.dbUrl }}:5432/fusionauth?timezone=UTC"
                    - name: FUSIONAUTH_APP_MEMORY
                      value: 768M
                    - name: FUSIONAUTH_SEARCH_MEMORY
                      value: 512M
                    - name: FUSIONAUTH_SEARCH_ENGINE_TYPE
                      value: database
                    - name: FUSIONAUTH_APP_RUNTIME_MODE 
                      value: production
                    - name: FUSIONAUTH_APP_SILENT_MODE
                      value: "true"
                    - name: DATABASE_MAXIMUM_POOL_SIZE
                      value: "32"
                    - name: DATABASE_CONNECTION_TIMEOUT
                      value: "20000"
                    - name: DATABASE_CONNECTION_HEALTHCHECK_99PERCENT_MS
                      value: "5000"
                    - name: DATABASE_ROOT_USER
                      valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: username
                    - name: DATABASE_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: password
                    - name: DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                            name: fusionauth-db-secret
                            key: username
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: fusionauth-db-secret
                            key: password