version: "3.8"
services:
  api:
    image: "registry.gitlab.com/squadov/squadovapiserver/${GCP_PROJECT}/squadov_api_server:latest"
    networks:
      squadov_c3p0:
          ipv4_address: "172.22.0.5"
  app:
    image: "registry.gitlab.com/squadov/squadovapiserver/${GCP_PROJECT}/squadov_webapp:latest"
    networks:
      squadov_c3p0:
          ipv4_address: "172.22.0.6"
networks:
  squadov_c3p0:
    external: true