apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: external-squadov-ingress
    annotations:
        kubernetes.io/ingress.global-static-ip-name: squadov-static-ip
        networking.gke.io/v1beta1.FrontendConfig: "squadov-frontend-config"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        acme.cert-manager.io/http01-edit-in-place: "true"
    labels:
        task: global
spec:
    rules:
        - host: "support.squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-support-service
                servicePort: 80
        - host: "squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-landing-service
                servicePort: 80
        - host: "www.squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-landing-service
                servicePort: 80
        - host: "auth.squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-fusionauth-service
                servicePort: 9011
        - host: "api.squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-api-service
                servicePort: 8080
        - host: "app.squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-app-service
                servicePort: 3000
        - host: "blog.squadov.gg"
          http:
            paths:
            - backend:
                serviceName: internal-blog-service
                servicePort: 80
    tls:
        - hosts:
            - "support.squadov.gg"
            - "www.squadov.gg"
            - "auth.squadov.gg"
            - "app.squadov.gg"
            - "api.squadov.gg"
            - "blog.squadov.gg"
          secretName: squadov-cert-prod